# Generated by Django 5.0.1 on 2024-01-13 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('successful', 'successful'), ('on-going', 'on-going'), ('check-out', 'check-out')], default='on-going', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 13, 17, 6, 25, 302052, tzinfo=datetime.timezone.utc)),
        ),
    ]
