# Generated by Django 5.0.1 on 2024-01-13 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 1, 13, 19, 3, 54, 967360, tzinfo=datetime.timezone.utc)),
        ),
    ]
